DATASET:
  TRAIN: "/home/qiuqiu/Desktop/coco2017/train2017.txt"
  VAL: "/home/qiuqiu/Desktop/coco2017/val2017.txt"
  NAMES: "dataset/coco128/coco.names"
MODEL:
  NC: 80
  INPUT_WIDTH: 512
  INPUT_HEIGHT: 512
TRAIN:
  LR: 0.001
  THRESH: 0.25
  WARMUP: true
  BATCH_SIZE: 64
  END_EPOCH: 350
  MILESTIONES:
    - 150
    - 250
    - 300